### ISSUE TITLE
Flutter build web --release Error

### ISSUE THREAD

**Issue by Prohemant001** [Hamad-Anwar/Flutter-Responsive-Portfolio-WebApp#1]
When trying to build the release of this flutter web app. I'm getting error like 

Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1396 bytes (99.5% reduction).      
Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Codepoint 32 not found in font, aborting.

Codepoint 32 not found in font, aborting.

Codepoint 32 not found in font, aborting.

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7704 bytes (99.5%
reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.   
Target web_release_bundle failed: IconTreeShakerException: Font subsetting failed with exit code -1.

To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command
#0      IconTreeShaker.subsetFont (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:216:7) 
<asynchronous suspension>
#1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:128:25)     
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:106:3)
<asynchronous suspension>
#4      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:401:29)
<asynchronous suspension>
#5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)        
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:198:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27) 
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)   
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                             35.7s
Exception: Failed to compile application for the Web.

**Comment by Hamad-Anwar** [comment]
run command
flutter clean
flutter build web --no-tree-shake-icons
also build apk file to test

**Comment by Prohemant001** [comment]
But Whenever testing for release performance. I ‘m getting this error. The normal build is just for developmental purpose and whereas build release is for production purpose. But the error sustains… Sent from Mail for Windows From: H4๛『Hammad』Sent: 26 August 2023 02:48 PMTo: Hamad-Anwar/Flutter-Responsive-Portfolio-WebAppCc: Prohemant001; AuthorSubject: Re: [Hamad-Anwar/Flutter-Responsive-Portfolio-WebApp] Flutter build web --release Error (Issue #1) run commandflutter cleanflutter build web --no-tree-shake-iconsalso build apk file to test—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
